/*
 * To chan    @Override
    public void paintIcon(Component c, Graphics g, int x, int y) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getIconWidth() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getIconHeight() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
ge this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud_mysql;
import com.sun.glass.events.WindowEvent;
import crud_mysql.*;
import java.awt.event.WindowStateListener;
import javax.swing.*;
import java.util.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.springframework.beans.BeansException;
import org.springframework.context.*;
import org.springframework.context.annotation.*;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.stereotype.Component;


/**
 *
 * @author ASUS
 */
@Component
public class MySQL extends javax.swing.JFrame {

    /**
     * Creates new form MySQL
     */
    public MySQL() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        usertxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        cellphonetxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        insertbutt = new javax.swing.JButton();
        clearbutt = new javax.swing.JButton();
        searchbutt = new javax.swing.JButton();
        deletebutt = new javax.swing.JButton();
        helpbutt = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        usertxt2 = new javax.swing.JTextField();
        passtxt2 = new javax.swing.JTextField();
        emailtxt2 = new javax.swing.JTextField();
        cellphonetxt2 = new javax.swing.JTextField();
        nametxt2 = new javax.swing.JTextField();
        agetxt2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updatebutt = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        urlpasstxt = new javax.swing.JTextField();
        urlusertxt = new javax.swing.JTextField();
        urltxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        labelnotif = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        testurl = new javax.swing.JButton();
        idtxt2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tables = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        MySQLtable = new javax.swing.JTable();
        urltabletxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        showbutt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MySQL Manager");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("IDentification NO :");

        jLabel2.setText("Username : ");

        jLabel3.setText("Password : ");

        jLabel4.setText("Email : ");

        jLabel5.setText("Cellphone : ");

        jLabel6.setText("Name : ");

        jLabel7.setText("Age : ");

        idtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idtxtKeyReleased(evt);
            }
        });

        insertbutt.setText("INSERT");
        insertbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertbuttActionPerformed(evt);
            }
        });

        clearbutt.setText("CLEAR");
        clearbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttActionPerformed(evt);
            }
        });

        searchbutt.setText("SEARCH");
        searchbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttActionPerformed(evt);
            }
        });

        deletebutt.setText("DELETE");
        deletebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttActionPerformed(evt);
            }
        });

        helpbutt.setText("HELP");
        helpbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbuttActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 102));

        updatebutt.setText("UPDATE");
        updatebutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebuttActionPerformed(evt);
            }
        });

        jTextField8.setEditable(false);
        jTextField8.setText("TEXT FIELDS FOR NEW DATA (current)");

        jTextField10.setEditable(false);
        jTextField10.setText("TEXT FIELDS FOR UPDATTING (future)");

        jLabel10.setText("D.B URL :");

        jLabel11.setText("D.B USERNAME :");

        jLabel12.setText("D.B PASSWORD :");

        urltxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                urltxtKeyReleased(evt);
            }
        });

        labelnotif.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jButton1.setText("LOAD ENTIRE DATABASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadbutt(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelnotif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelnotif, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        testurl.setText("CONNECT TO DB");
        testurl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testurlActionPerformed(evt);
            }
        });

        idtxt2.setEditable(false);

        Tables.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tables_In_DB"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tables);

        MySQLtable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MySQLtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MySQLtable);

        jLabel13.setText("D.B TABLES :");

        showbutt.setText("SHOW TABLES");
        showbutt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbuttActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urltxt, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                    .addComponent(urlusertxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(urlpasstxt)
                                    .addComponent(urltabletxt, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(testurl, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(showbutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cellphonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(passtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(emailtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clearbutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(agetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cellphonetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(updatebutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nametxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(helpbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(idtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(insertbutt, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(deletebutt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(idtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertbutt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(usertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usertxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailtxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clearbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cellphonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cellphonetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updatebutt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nametxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(helpbutt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9)
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(urltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(urlusertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showbutt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(urlpasstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testurl))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(urltabletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void clearbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttActionPerformed
        // TODO add your handling code here:
        
        agetxt.setText("");
        usertxt.setText("");
        passtxt.setText("");
        idtxt.setText("");
        emailtxt.setText("");
        cellphonetxt.setText("");
        nametxt.setText("");
        idtxt2.setText("");
    }//GEN-LAST:event_clearbuttActionPerformed

    private void insertbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertbuttActionPerformed
        
      try {
            sql.Inserting(usertxt.getText(), passtxt.getText(), nametxt.getText(), cellphonetxt.getText(), emailtxt.getText(), Integer.parseInt(idtxt.getText()), Integer.parseInt(agetxt.getText()));
            agetxt.setText("");
            usertxt.setText("");
            passtxt.setText("");
            idtxt.setText("");
            emailtxt.setText("");
            cellphonetxt.setText("");
            nametxt.setText("");
            idtxt2.setText("");
        } catch (ClassNotFoundException | IllegalAccessException | SQLException | InstantiationException ex) {
            Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
            this.labelnotif.setText("you Do NOT HAVE ANY CONNECTIO NOW ! :((");
        }
    }//GEN-LAST:event_insertbuttActionPerformed
    
    private void loadbutt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadbutt
        try {
            // TODO add your handling code here:

            sql.LoadingEntireData(MySQLtable);
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
            this.labelnotif.setText("you Do NOT HAVE ANY CONNECTIO NOW ! :((");
        }
        
        
    }//GEN-LAST:event_loadbutt

    private void helpbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbuttActionPerformed
        // TODO add your handling code here:
        
        HELP hlp = new HELP();
        hlp.show();
        
    }//GEN-LAST:event_helpbuttActionPerformed

    private void updatebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebuttActionPerformed
        // TODO add your handling code here:
        
        if(("".equals(this.idtxt.getText())) & ("".equals(this.usertxt.getText())))
        {
            this.labelnotif.setText("One of username & ID is requirement for updating :))");
        }else{
            
            if(("".equals(this.usertxt.getText())))
            {
                this.usertxt.setText(" ");
            }
            
            if(("".equals(this.idtxt.getText())))
            {
                this.idtxt.setText("0");
            }
            
            try{
                Inputs_2 in2 = (Inputs_2) ctx.getBean("inputs");
                in2.setId(Integer.parseInt(this.idtxt.getText()));
                in2.setUser(this.usertxt.getText());
                
                Input_update inup = (Input_update) ctx.getBean("update");
                inup.setUser(this.usertxt2.getText());
                inup.setPass(this.passtxt2.getText());
                inup.setAge(Integer.parseInt(this.agetxt2.getText()));
                inup.setEmail(this.emailtxt2.getText());
                inup.setName(this.nametxt2.getText());
                inup.setCellphone(this.cellphonetxt2.getText());
                sql.Update(MySQLtable);
                
            }catch(BeansException ex)
            {
                throw ex;
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
                ex.printStackTrace();
                Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
                this.labelnotif.setText("something went wrong during update process :(( ");
            }
        }
        
        
    }//GEN-LAST:event_updatebuttActionPerformed

    private void deletebuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttActionPerformed
        try {
            // TODO add your handling code here:
            
            if("".equals(idtxt.getText()))
            {
                labelnotif.setText("You DO NOT ENTER THE ID :((");
            }
            
            sql.Delete(Integer.parseInt(idtxt.getText()));
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
            Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
            this.labelnotif.setText("you Do NOT HAVE ANY CONNECTIO NOW ! :((");
        }
        agetxt.setText("");
        usertxt.setText("");
        passtxt.setText("");
        idtxt.setText("");
        emailtxt.setText("");
        cellphonetxt.setText("");
        nametxt.setText("");
        idtxt2.setText("");
    }//GEN-LAST:event_deletebuttActionPerformed

    private void urltxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_urltxtKeyReleased
        // TODO add your handling code here:
        
        if("".equals(urltxt.getText()))
        {
            labelnotif.setText("Oh, This can't be GOOD FILL the URL NOW !!");
        } 
    }//GEN-LAST:event_urltxtKeyReleased

    private void idtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idtxtKeyReleased
        // TODO add your handling code here:
        
        idtxt2.setText(idtxt.getText());
    }//GEN-LAST:event_idtxtKeyReleased

    private void testurlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testurlActionPerformed
        // TODO add your handling code here:
        URLs url = (URLs) ctx.getBean("url");
        url.setUrl(urltxt.getText());
        url.setPass(urlpasstxt.getText());
        url.setUser(urlusertxt.getText());
        url.setTablename(urltabletxt.getText());
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            try (Connection connect = DriverManager.getConnection(this.urltxt.getText(), this.urlusertxt.getText(), this.urlpasstxt.getText())) {
                labelnotif.setText("Connection Activated ! :)) ");
                urltxt.setText("");
                urlusertxt.setText("");
                urlpasstxt.setText("");
                urltabletxt.setText("");
            }
            
        }
        catch(ClassNotFoundException | IllegalAccessException | InstantiationException ex)
        {
            
        } catch (SQLException ex) {
            Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
            labelnotif.setText("Connection Deactivated ! :((");
        }
    }//GEN-LAST:event_testurlActionPerformed

    
    private void searchbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttActionPerformed
        // TODO add your handling code here:
        
        
        if(("".equals(this.idtxt.getText())))
        {
            this.idtxt.setText("0");
            
        }
        
        if(("".equals(this.idtxt.getText())))
        {
            this.usertxt.setText(" ");
        }
        
        if("".equals(this.nametxt.getText()))
        {
            this.nametxt.setText(" ");
        }
        
        if("".equals(this.emailtxt.getText()))
        {
            this.emailtxt.setText(" ");
        }
        
        if("".equals(this.agetxt.getText()))
        {
            this.agetxt.setText("0");
        }
        
        try
        {
            Inputs_2 in2 = (Inputs_2) ctx.getBean("inputs");
        
            
            in2.setUser(usertxt.getText());
            in2.setName(nametxt.getText());
            in2.setEmail(emailtxt.getText());
            in2.setAge(Integer.parseInt(agetxt.getText()));
            
            try{
                
                in2.setId(Integer.parseInt(idtxt.getText()));
                in2.setAge(Integer.parseInt(agetxt.getText()));
            } catch(ArithmeticException ex){
                Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
                this.labelnotif.setText("May Be you Entered some characters for ID & Age checkboxes.");
                throw ex;
            }
            
            try {
                sql.Searching(MySQLtable);
            } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex) {
                Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
                this.labelnotif.setText("Something went wrong :(( ");
            }
            
            agetxt.setText("");
            usertxt.setText("");
            passtxt.setText("");
            idtxt.setText("");
            emailtxt.setText("");
            cellphonetxt.setText("");
            nametxt.setText("");
            idtxt2.setText("");
        }
        catch(NumberFormatException | BeansException ex)
        {
            this.labelnotif.setText("Something Occur to Show the Searching Result :(( ");
            throw ex;
        }
        
    }//GEN-LAST:event_searchbuttActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Welcome to the MYSQL Manager !", "Welcome", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_formWindowOpened

    private void showbuttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbuttActionPerformed
        // TODO add your handling code here:
        
        URLs url = (URLs) ctx.getBean("url");
        url.setUrl(urltxt.getText());
        url.setPass(urlpasstxt.getText());
        url.setUser(urlusertxt.getText());
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection connect = DriverManager.getConnection(url.getUrl(),url.getUser(),url.getPass());
            Statement state = connect.createStatement();
            String query = "show tables";
            ResultSet result = state.executeQuery(query);
            DefaultTableModel dtm = (DefaultTableModel) this.Tables.getModel();
            int rows = dtm.getRowCount();
            for(int i = rows - 1;i>=0;i--)
            {
                dtm.removeRow(i);
            }
            
            while(result.next())
            {
                String name = result.getString(1);
                Vector content = new Vector();
                content.addElement(name);
                dtm.addRow(content);
           }
            this.labelnotif.setText("Now this is your Tables from your DB ! ;)) ");
        }catch(ClassNotFoundException | IllegalAccessException | InstantiationException | SQLException ex)
        {
                Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
                this.labelnotif.setText("Something went wrong from loading tables in the DB :(( ");
                urltxt.setText("");
                urlusertxt.setText("");
                urlpasstxt.setText("");
                urltabletxt.setText("");
        }
        
    }//GEN-LAST:event_showbuttActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MySQL().setVisible(true);
        });
    }
    ApplicationContext ctx = new AnnotationConfigApplicationContext(Config.class);
    CRUD_MySQL sql = (CRUD_MySQL) ctx.getBean("crud");
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MySQLtable;
    private javax.swing.JTable Tables;
    private javax.swing.JTextField agetxt;
    private javax.swing.JTextField agetxt2;
    private javax.swing.JTextField cellphonetxt;
    private javax.swing.JTextField cellphonetxt2;
    private javax.swing.JButton clearbutt;
    private javax.swing.JButton deletebutt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField emailtxt2;
    private javax.swing.JButton helpbutt;
    private javax.swing.JTextField idtxt;
    private javax.swing.JTextField idtxt2;
    private javax.swing.JButton insertbutt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel labelnotif;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nametxt2;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField passtxt2;
    private javax.swing.JButton searchbutt;
    private javax.swing.JButton showbutt;
    private javax.swing.JButton testurl;
    private javax.swing.JButton updatebutt;
    private javax.swing.JTextField urlpasstxt;
    private javax.swing.JTextField urltabletxt;
    private javax.swing.JTextField urltxt;
    private javax.swing.JTextField urlusertxt;
    private javax.swing.JTextField usertxt;
    private javax.swing.JTextField usertxt2;
    // End of variables declaration//GEN-END:variables
}
